#!/usr/bin/env bash
# Install nginx on your web-01
# server
# Nginx should be listening on port 80
# When querying Nginx at its root / with a GET request (requesting a page) using curl,
#  .it must return a page that contains the string Hello World!
sudo apt-get -y update
sudo apt-get -y install nginx
sudo sh -c 'cat <<EOF > /etc/nginx/sites-available/default
server {
  listen 80;
  server_name localhost:

  location / {
    root /var/www/html;
    index index.html;
  }
}
EOF'

sudo sh -c 'echo "Hello World!" > /var/www/html/index.html'

# Restart Nginx
sudo service nginx start
