#!/usr/bin/env bash
# Install nginx on your web-01
# server
# Nginx should be listening on port 80
# When querying Nginx at its root / with a GET request (requesting a page) using curl,
#  .it must return a page that contains the string Hello World!

# Install nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# root display msg
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'

# Redirect
redirect_rule="return 301 https://youtu.be/KTiiwdaL7ac?si=FMYBhabp8hwf4Gq6"
old="server_name _;"
new="server_name _;\n\n\tlocation /redirect_me {\n\t\t$redirect_rule;\n\t}"

sudo sed -i --follow-symlinks -e "s|$old|$new|" /etc/nginx/sites-enabled/default

# Start server
sudo service nginx start
