#!/usr/bin/env bash
# Install nginx on your web-01
# server
# Nginx should be listening on port 80
# When querying Nginx at its root / with a GET request (requesting a page) using curl,
#  .it must return a page that contains the string Hello World!

# Install nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# allow nginx on firewall
sudo ufw allow 'Nginx HTTP'

# Permisions
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# root display msg
echo -e "Hello World!" > /var/www/html/index.nginx-debian.html

# Set 404 page
touch /var/www/html/e_404.html
echo -e "Ceci n'est pas une page" >> /var/www/html/e_404.html
sudo sed -i "/server_name _;/a \ \n\terror_page 404 /e_404.html;" /etc/nginx/sites-available/default

# Redirect
redirect_rule="return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4"
old="server_name _;"
new="\n\n\tlocation /redirect_me {\n\t\t$redirect_rule;\n\t}"

sudo sed -i  "/$old/a \ $new" /etc/nginx/sites-available/default

# Start server
sudo service nginx start
