#!/usr/bin/bash
# Nginx running, and listening on port 80 of all the server’s active IPv4 IPs
sudo sed -i "s/8080/80" /etc/nginx/sites-available/default
sudo service nginx restart
sudo rm /run/nginx.pid
