#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd, using the while loop + IFS

# Specify the file path
passwd_file="/etc/passwd"

# Check if the file exists
if [ -e "$passwd_file" ]; then
    # Use a while loop to read each line from the file
    while IFS=: read -r username passwd uid GID UIDI home CMD; do
        # Display the required information
        echo "The user $username is part of the $GID gang, lives in $home and rides $CMD. $uid's place is protected by the passcode $passwd, more info about the user here: $UIDI"
    done < "$passwd_file"
else
    echo "Error: $passwd_file does not exist."
fi
