#!/usr/bin/env bash
# Bash script to display "Best School" 10 times using a while loop
# And Hi on the 9th

# Initialize a counter
counter=0
# While loop to display "Best School" until the counter reaches 10
while [ $counter -lt 10 ]; do
    echo "Best School"
    # Increment the counter
    ((counter++))

	if [ "$counter" -eq 9 ]
	then
		echo "Hi"
	fi
    
done
