#!/usr/bin/env bash
# Bash script to display "Best School" 10 times using a while loop

# Initialize a counter
counter=0
# While loop to display "Best School" until the counter reaches 10
while [ $counter -lt 10 ]; do
    # Increment the counter
    ((counter++))

	if [ "$counter" -eq 4 ]; then
		echo "bad luck"
	elif [ "$counter" -eq 8 ]; then
		echo "good luck"
	else
    	echo "Best School"
	fi
    
done
