#!/usr/bin/env bash
# Bash script to display time for 12 hours and 59 minutes using a while loop

# Initialize hours and minutes
hour=0

# While loop to display time
while [ $hour -le 12 ]; do
    minute=1
    echo "Hour: $hour"
    while [ $minute -le 59 ]; do
		echo "$minute"

        # Increment minute
        ((minute++))
    done
    
    # Increment hour
    ((hour++))
done
