#!/usr/bin/env bash
# kill apache2, set up nginx listning on 8080
pkill apache2
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sed -i 's/#user www-data/user nginx/g' /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service restart nginx
